version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - postgres
      - redis
    networks:
      - gommerce-network

  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - gommerce-network
    # volumes:
    #   - database-postgres:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"      
    # environment:
    #   - REDIS_PASSWORD=${REDIS_PASS}       
    networks:
      - gommerce-network

networks:
  gommerce-network: